# Generated by Django 5.1.7 on 2025-04-17 04:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('publication_date', models.DateField()),
                ('citations', models.PositiveIntegerField(default=0)),
                ('available_copies', models.PositiveIntegerField(default=1)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='papers/')),
                ('program', models.CharField(choices=[('MAgDev-AE', 'Master of Agricultural Development - Agricultural Extension'), ('BSA-CS', 'Bachelor of Science in Agriculture - Crop Science'), ('BSA-AS', 'Bachelor of Science in Agriculture - Animal Science'), ('MAEd-EA', 'Master of Arts in Education - Educational Administration'), ('BEEd', 'Bachelor of Elementary Education'), ('BPEd', 'Bachelor of Physical Education'), ('BSEd-ENG', 'Bachelor of Secondary Education - English'), ('BSEd-MATH', 'Bachelor of Secondary Education - Mathematics'), ('BSIT', 'Bachelor of Science in Information Technology'), ('BSCrim', 'Bachelor of Science in Criminology'), ('BSISM', 'Bachelor of Science in Industrial Security Management')], default='BSIT', max_length=100)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('authors', models.ManyToManyField(related_name='papers', to='scholar.author')),
                ('viewers', models.ManyToManyField(blank=True, related_name='viewed_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reserved', 'Reserved')], default='pending', max_length=10)),
                ('return_status', models.CharField(blank=True, choices=[('pending', 'Pending Return Approval'), ('approved', 'Return Approved'), ('rejected', 'Return Rejected')], max_length=10, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('borrow_reason', models.TextField(blank=True, help_text='Reason for borrowing this paper', null=True)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar.paper')),
            ],
            options={
                'ordering': ['-borrow_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('program', models.CharField(choices=[('MAgDev-AE', 'Master of Agricultural Development - Agricultural Extension'), ('BSA-CS', 'Bachelor of Science in Agriculture - Crop Science'), ('BSA-AS', 'Bachelor of Science in Agriculture - Animal Science'), ('MAEd-EA', 'Master of Arts in Education - Educational Administration'), ('BEEd', 'Bachelor of Elementary Education'), ('BPEd', 'Bachelor of Physical Education'), ('BSEd-ENG', 'Bachelor of Secondary Education - English'), ('BSEd-MATH', 'Bachelor of Secondary Education - Mathematics'), ('BSIT', 'Bachelor of Science in Information Technology'), ('BSCrim', 'Bachelor of Science in Criminology'), ('BSISM', 'Bachelor of Science in Industrial Security Management')], max_length=100)),
                ('year_level', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_date', models.DateField(auto_now_add=True)),
                ('cited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_papers', to='scholar.paper')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_citations', to='scholar.paper')),
            ],
            options={
                'unique_together': {('paper', 'cited_by')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar.paper')),
            ],
            options={
                'unique_together': {('user', 'paper')},
            },
        ),
    ]
