# Generated by Django 5.1.7 on 2025-04-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='notification_read',
            field=models.BooleanField(default=False, help_text='Whether the approval notification has been read'),
        ),
    ]
