# Generated by Django 5.1.5 on 2025-01-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='introduction',
            field=models.TextField(blank=True, help_text='Introduction section of the paper'),
        ),
    ]
