# Generated by Django 5.1.7 on 2025-04-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0002_borrow_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting this borrow request', null=True),
        ),
    ]
