# Generated by Django 5.1.5 on 2025-02-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0002_borrow_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='borrow',
            name='return_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Return Approval'), ('approved', 'Return Approved'), ('rejected', 'Return Rejected')], max_length=10, null=True),
        ),
    ]
