# Generated by Django 5.1.5 on 2025-02-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0003_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='paper',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(related_name='papers', to='scholar.author'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='available_copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='paper',
            name='citations',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
