# Generated by Django 5.1.5 on 2025-02-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0003_remove_borrow_is_returned_borrow_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
