# Generated by Django 5.1.5 on 2025-02-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0004_borrow_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
