# Generated by Django 5.1.5 on 2025-02-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0005_paper_viewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='papers/'),
        ),
    ]
