# Generated by Django 5.1.7 on 2025-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0006_paper_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('MAgDev-AE', 'Master of Agricultural Development - Agricultural Extension'), ('BSA-CS', 'Bachelor of Science in Agriculture - Crop Science'), ('BSA-AS', 'Bachelor of Science in Agriculture - Animal Science'), ('MAEd-EA', 'Master of Arts in Education - Educational Administration'), ('BEEd', 'Bachelor of Elementary Education'), ('BPEd', 'Bachelor of Physical Education'), ('BSEd-ENG', 'Bachelor of Secondary Education - English'), ('BSEd-MATH', 'Bachelor of Secondary Education - Mathematics'), ('BSIT', 'Bachelor of Science in Information Technology'), ('BSCrim', 'Bachelor of Science in Criminology'), ('BSISM', 'Bachelor of Science in Industrial Security Management')], max_length=100),
        ),
    ]
