# Generated by Django 5.1.7 on 2025-04-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0009_borrow_borrow_reason_borrow_request_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
